dataset:
  name: 'coco'

model:
  name: 'teran'
  embed-size: 768
  text-aggregation: 'first'
  image-aggregation: 'first'
  freeze-teran: False         # the vin-vl backbone is trainable
  teran-layers: 0
  tern-layers: 2              # number of TE layers in the matching head (not used in this case, as we are training the alignment head only)
  post-layers: 0
  exclude-stopwords: False
  shared-transformer: True
  depth-aggregation-alignment: False
  depth-aggregation-matching: False
  dropout: 0.1

training:
  lr: 0.00001  # 0.000006
  grad-clip: 2.0
  max-violation: True
  loss-type: 'alignment-distillation'      # 'train the alignment head using hinge-based triplet loss, and at the same time learn the matching head using distillation
  loss-weights: [1, 1]
  alignment-mode: 'MrSw'      # alignment: max over image regions, sum over the words
  distillation-mode: 'listnet'
  activate_distillation_after: 0  # activate the distillation immediately (need to start with a pre-trained backbone)
  measure: 'dot'
  margin: 0.2                 # hinge-based triplet loss margin (alpha)
  bs: 32

  scheduler: 'steplr'
  gamma: 0.1
  step-size: 15
  warmup: null
  warmup-period: 1000