dataset:
  name: 'coco'
  images-path: 'data/coco/images'  # not needed if using pre-extracted bottom-up features
  data: '/media/nicola/SSD/VSEpp_ExtractedFeatures/'
  restval: True
  pre-extracted-features: False

text-model:
  name: 'bert'
  pretrain: 'bert-base-uncased'
  word-dim: 768
  extraction-hidden-layer: 6
  fine-tune: True
  pre-extracted: False
  layers: 0
  dropout: 0.1

#text-model:
#  name: 'gru'
#  word-dim: 300
#  fine-tune: True
#  pre-extracted: False
#  layers: 1

image-model:
  name: 'bottomup'
  pre-extracted-features-root: 'data/coco/features_36'
  transformer-layers: 4
  dropout: 0.1
  pos-encoding: null
  crop-size: 224  # not used
  fine-tune: False
  feat-dim: 2048
  norm: True

model:
  name: 'teran'
  embed-size: 768
  text-aggregation: 'first'
  image-aggregation: 'first'
  freeze-teran: True
  teran-layers: 0
  tern-layers: 2
  post-layers: 0
  exclude-stopwords: False
  shared-transformer: True
  depth-aggregation-alignment: False # 'gated', 'mean' or null
  depth-aggregation-matching: 'gated'
  dropout: 0.1

training:
  lr: 0.00001  # 0.000006
  grad-clip: 2.0
  max-violation: True
  loss-type: 'matching' # 'selfaggregation-entropy' #'distillation'
  loss-weights: 'auto'
  alignment-mode: 'MrSw'
  distillation-mode: 'listnet'
  measure: 'dot'
  margin: 0.2
  bs: 32
  scheduler: 'steplr'
  gamma: 0.1
  step-size: 10
  warmup: null
  warmup-period: 1000
